### ISSUE TITLE
AbstractModel.php setOpt Method does nothing

### ISSUE THREAD

**Issue by techteam-seobility** [jovixv/DFSClient-v3#15]
AbstractModel.php setOpt Method is empty, but used in RelatedKeywords.php

So Setting a Keyword in RelatedKeywords.php does effectively nothing. I'm not shure if this should be fixed or removed. As the documentation for setOpt is also empty.

**Comment by vadmou** [comment]
Hello,

Thank you for reporting this issue.

The RelatedKeywords.php file is now deprecated. Please use the following updated implementations instead:

- Models/DataForSeoLabsApi/Google/GoogleRelatedKeywordsLive.php
- Models/DataForSeoLabsApi/Bing/BingRelatedKeywordsLive.php
- Models/DataForSeoLabsApi/Amazon/AmazonRelatedKeywordsLive.php
