### ISSUE TITLE
Error while installing through composer 

### ISSUE THREAD

**Issue by nikita2811** [jovixv/DFSClient-v3#26]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires jovix/dataforseo-clientv3 dev-master -> satisfiable by jovix/dataforseo-clientv3[dev-master].
    - jovix/dataforseo-clientv3 dev-master requires symfony/var-dumper ^4.1 -> found symfony/var-dumper[v4.1.0-BETA1, ..., 4.4.x-dev] but it conflicts with your root composer.json require (^5.3).

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by dukenst2006** [comment]
Hi,
I get the same error, trying to install on laravel 8. any update ?

**Comment by jovixv** [comment]
@dukenst2006, @nikita2811. Hi, tomorrow will be release for laravel 8 and PHP >= 7.4

**Comment by dukenst2006** [comment]
Thx @jovixv , this is a good news. And about documentation for this repository?
Thanks again for this quick reply.
