### ISSUE TITLE
Syntax Errors

### ISSUE THREAD

**Issue by webtoolsde** [jovixv/DFSClient-v3#27]
<img width="458" alt="grafik" src="https://user-images.githubusercontent.com/5220380/153559822-060b629b-5a33-4d1f-be93-82c8c1bb485f.png">

!!  08:27:14 CRITICAL  [php] Uncaught Error: syntax error, unexpected '.', expecting ';' or ',' ["exception" => ParseError { …}]
!!  
!!  In BackLinksAvailableFiltersEntityMainTasksResultAnchors.php line 41:
!!                                                        
!!    syntax error, unexpected '.', expecting ';' or ','  
!!                    

I think this error is at a lot of more places.

**Comment by vadmou** [comment]
Hello,
Thank you for reporting this issue. It has been fixed. Please download the latest release of the library (v1.2.7).
