### ISSUE TITLE
API response data is gibberish

### ISSUE THREAD

**Issue by azam1** [jovixv/DFSClient-v3#57]
When I use the endpoint https://api.dataforseo.com/v3/business_data/google/my_business_info/live my response data is gibberish, it shows the results count and everything right but the text is just gibberish. When I do the same call using postman I am getting the correct response. I am using this with laravel. Not sure if its only related to this endpoint or others as well.

**Comment by azam1** [comment]
Also, the task ID comes as "00000000-0000-0000-0000-000000000000", all the time. The same request works fine in postman.

**Comment by vadmou** [comment]
Hello,

Could you please provide details on how exactly you are making the request?

On our end, we tested the following example:

```php
$model = new \DFSClientV3\Models\BusinessDataApi\Google\BusinessInfo\BusinessInfoLive();  
$model->setLanguageCode('en');  
$model->setLocationCode(2840);  
$model->setKeyword('cid:194604053573767737');  
print_r($model->getAsJson());
```

It returned correct and up-to-date data.
